# Starts the full proxy stack for Codex:
#   Node bridge (port 4201, /v1/models fix) + LiteLLM (port 4200, Responses->chat bridge)
# Usage: pwsh -File "start-litellm.ps1"  (normally launched by codex-launch.ps1)
$dir = $PSScriptRoot   # auto-locates: the script finds its .env/config.yaml wherever it is

function Port-Up([int]$p) {
  try { $t = New-Object Net.Sockets.TcpClient; $t.Connect('127.0.0.1', $p); $t.Close(); return $true }
  catch { return $false }
}

# Force UTF-8 (otherwise the LiteLLM banner crashes the Windows cp1252 console)
$env:PYTHONUTF8 = "1"
$env:PYTHONIOENCODING = "utf-8"

# config.yaml is generated by codex-launch.ps1 (wildcard '*' -> menu provider)
if (-not (Test-Path "$dir\config.yaml")) {
  Write-Host "[!] config.yaml not found: run codex-launch.ps1 (menu) first" -ForegroundColor Red
  exit 1
}

# .env is required: copy .env.example to .env and fill in your own API keys
if (-not (Test-Path "$dir\.env")) {
  Write-Host "[!] .env not found: copy .env.example to .env and fill in your API keys" -ForegroundColor Red
  exit 1
}

# Load keys from .env into the process environment
Get-Content "$dir\.env" | ForEach-Object {
  if ($_ -match '^\s*([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.+)$') {
    $name = $matches[1]; $val = $matches[2]
    $val = $val.Trim().Trim('"').Trim("'")   # strip optional quotes
    if ($val) { Set-Item -Path "Env:$name" -Value $val }
  }
}

# Validate that ALL keys referenced by config.yaml are present and non-empty
$required = Select-String -Path "$dir\config.yaml" -Pattern 'os\.environ/([A-Z0-9_]+)' -AllMatches |
  ForEach-Object { $_.Matches } | ForEach-Object { $_.Groups[1].Value } | Sort-Object -Unique
$missing = @($required | Where-Object { -not (Get-Item "Env:$_" -ErrorAction SilentlyContinue).Value })
if ($missing.Count -gt 0) {
  Write-Host "[!] missing or empty keys in .env: $($missing -join ', ')" -ForegroundColor Red
  exit 1
}
Write-Host "[ok] keys loaded: $($required -join ', ')"

# Node bridge 4201: Codex expects {"models":[...]} on /v1/models, LiteLLM returns {"data":[...]}.
# The home's config.toml points to 4201; the bridge forwards everything to LiteLLM on 4200.
if (-not (Port-Up 4201)) {
  if (-not (Get-Command node -ErrorAction SilentlyContinue)) {
    Write-Host "[!] node not found - the 4201 bridge cannot start" -ForegroundColor Red
    exit 1
  }
  Start-Process node -ArgumentList "`"$dir\codex-litellm-proxy.js`"" -WindowStyle Hidden
  $up = $false
  for ($i = 0; $i -lt 20; $i++) { Start-Sleep -Milliseconds 500; if (Port-Up 4201) { $up = $true; break } }
  if (-not $up) { Write-Host "[!] 4201 bridge not ready after 10s" -ForegroundColor Red; exit 1 }
}
Write-Host "[ok] Codex->LiteLLM bridge active on 4201"

# Start the proxy on port 4200 (loopback only)
# IMPORTANT: Set-Location so Python can find codex_deepseek_fix.py via CWD
Set-Location -Path $dir
litellm --config "$dir\config.yaml" --host 127.0.0.1 --port 4200
